/*
 * generated by Xtext 2.22.0
 */
package org.xtext.sisprog;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class P2StandaloneSetup extends P2StandaloneSetupGenerated {

	public static void doSetup() {
		new P2StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
