/*
 * generated by Xtext 2.22.0
 */
package org.xtext.sisprog.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.sisprog.parser.antlr.internal.InternalP2Parser;
import org.xtext.sisprog.services.P2GrammarAccess;

public class P2Parser extends AbstractAntlrParser {

	@Inject
	private P2GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalP2Parser createParser(XtextTokenStream stream) {
		return new InternalP2Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Programa";
	}

	public P2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(P2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
