/*
 * generated by Xtext 2.22.0
 */
package org.xtext.sisprog.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class P2UiModule extends AbstractP2UiModule {

	public P2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
