/**
 * generated by Xtext 2.22.0
 */
package org.xtext.sisprog.p2;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atribuicao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sisprog.p2.Atribuicao#getRes <em>Res</em>}</li>
 *   <li>{@link org.xtext.sisprog.p2.Atribuicao#getAt <em>At</em>}</li>
 * </ul>
 *
 * @see org.xtext.sisprog.p2.P2Package#getAtribuicao()
 * @model
 * @generated
 */
public interface Atribuicao extends Comando
{
  /**
   * Returns the value of the '<em><b>Res</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Res</em>' containment reference.
   * @see #setRes(variavel)
   * @see org.xtext.sisprog.p2.P2Package#getAtribuicao_Res()
   * @model containment="true"
   * @generated
   */
  variavel getRes();

  /**
   * Sets the value of the '{@link org.xtext.sisprog.p2.Atribuicao#getRes <em>Res</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Res</em>' containment reference.
   * @see #getRes()
   * @generated
   */
  void setRes(variavel value);

  /**
   * Returns the value of the '<em><b>At</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>At</em>' containment reference.
   * @see #setAt(Aritmetico)
   * @see org.xtext.sisprog.p2.P2Package#getAtribuicao_At()
   * @model containment="true"
   * @generated
   */
  Aritmetico getAt();

  /**
   * Sets the value of the '{@link org.xtext.sisprog.p2.Atribuicao#getAt <em>At</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>At</em>' containment reference.
   * @see #getAt()
   * @generated
   */
  void setAt(Aritmetico value);

} // Atribuicao
