/**
 * generated by Xtext 2.22.0
 */
package org.xtext.sisprog.p2;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comparacao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sisprog.p2.Comparacao#getOp1 <em>Op1</em>}</li>
 *   <li>{@link org.xtext.sisprog.p2.Comparacao#getOpr <em>Opr</em>}</li>
 *   <li>{@link org.xtext.sisprog.p2.Comparacao#getOp2 <em>Op2</em>}</li>
 * </ul>
 *
 * @see org.xtext.sisprog.p2.P2Package#getComparacao()
 * @model
 * @generated
 */
public interface Comparacao extends EObject
{
  /**
   * Returns the value of the '<em><b>Op1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op1</em>' containment reference.
   * @see #setOp1(Expressao)
   * @see org.xtext.sisprog.p2.P2Package#getComparacao_Op1()
   * @model containment="true"
   * @generated
   */
  Expressao getOp1();

  /**
   * Sets the value of the '{@link org.xtext.sisprog.p2.Comparacao#getOp1 <em>Op1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op1</em>' containment reference.
   * @see #getOp1()
   * @generated
   */
  void setOp1(Expressao value);

  /**
   * Returns the value of the '<em><b>Opr</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Opr</em>' attribute list.
   * @see org.xtext.sisprog.p2.P2Package#getComparacao_Opr()
   * @model unique="false"
   * @generated
   */
  EList<String> getOpr();

  /**
   * Returns the value of the '<em><b>Op2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op2</em>' containment reference.
   * @see #setOp2(Expressao)
   * @see org.xtext.sisprog.p2.P2Package#getComparacao_Op2()
   * @model containment="true"
   * @generated
   */
  Expressao getOp2();

  /**
   * Sets the value of the '{@link org.xtext.sisprog.p2.Comparacao#getOp2 <em>Op2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op2</em>' containment reference.
   * @see #getOp2()
   * @generated
   */
  void setOp2(Expressao value);

} // Comparacao
