/**
 * generated by Xtext 2.22.0
 */
package org.xtext.sisprog.p2;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Desvio Condicional</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sisprog.p2.DesvioCondicional#getComparacao <em>Comparacao</em>}</li>
 *   <li>{@link org.xtext.sisprog.p2.DesvioCondicional#getComandos <em>Comandos</em>}</li>
 *   <li>{@link org.xtext.sisprog.p2.DesvioCondicional#getComando <em>Comando</em>}</li>
 * </ul>
 *
 * @see org.xtext.sisprog.p2.P2Package#getDesvioCondicional()
 * @model
 * @generated
 */
public interface DesvioCondicional extends Comando
{
  /**
   * Returns the value of the '<em><b>Comparacao</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sisprog.p2.Comparacao}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparacao</em>' containment reference list.
   * @see org.xtext.sisprog.p2.P2Package#getDesvioCondicional_Comparacao()
   * @model containment="true"
   * @generated
   */
  EList<Comparacao> getComparacao();

  /**
   * Returns the value of the '<em><b>Comandos</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sisprog.p2.Comando}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comandos</em>' containment reference list.
   * @see org.xtext.sisprog.p2.P2Package#getDesvioCondicional_Comandos()
   * @model containment="true"
   * @generated
   */
  EList<Comando> getComandos();

  /**
   * Returns the value of the '<em><b>Comando</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sisprog.p2.Comando}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comando</em>' containment reference list.
   * @see org.xtext.sisprog.p2.P2Package#getDesvioCondicional_Comando()
   * @model containment="true"
   * @generated
   */
  EList<Comando> getComando();

} // DesvioCondicional
