/**
 * generated by Xtext 2.22.0
 */
package org.xtext.sisprog.p2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expressao</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.sisprog.p2.P2Package#getExpressao()
 * @model
 * @generated
 */
public interface Expressao extends EObject
{
} // Expressao
