/**
 * generated by Xtext 2.22.0
 */
package org.xtext.sisprog.p2;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Funcao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sisprog.p2.Funcao#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.sisprog.p2.Funcao#getComandos <em>Comandos</em>}</li>
 * </ul>
 *
 * @see org.xtext.sisprog.p2.P2Package#getFuncao()
 * @model
 * @generated
 */
public interface Funcao extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.sisprog.p2.P2Package#getFuncao_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.sisprog.p2.Funcao#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Comandos</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sisprog.p2.Comando}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comandos</em>' containment reference list.
   * @see org.xtext.sisprog.p2.P2Package#getFuncao_Comandos()
   * @model containment="true"
   * @generated
   */
  EList<Comando> getComandos();

} // Funcao
