/**
 * generated by Xtext 2.22.0
 */
package org.xtext.sisprog.p2;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.sisprog.p2.P2Package
 * @generated
 */
public interface P2Factory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  P2Factory eINSTANCE = org.xtext.sisprog.p2.impl.P2FactoryImpl.init();

  /**
   * Returns a new object of class '<em>Programa</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Programa</em>'.
   * @generated
   */
  Programa createPrograma();

  /**
   * Returns a new object of class '<em>Funcao</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Funcao</em>'.
   * @generated
   */
  Funcao createFuncao();

  /**
   * Returns a new object of class '<em>Comando</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Comando</em>'.
   * @generated
   */
  Comando createComando();

  /**
   * Returns a new object of class '<em>Desvio Condicional</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Desvio Condicional</em>'.
   * @generated
   */
  DesvioCondicional createDesvioCondicional();

  /**
   * Returns a new object of class '<em>Comparacao</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Comparacao</em>'.
   * @generated
   */
  Comparacao createComparacao();

  /**
   * Returns a new object of class '<em>Atribuicao</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Atribuicao</em>'.
   * @generated
   */
  Atribuicao createAtribuicao();

  /**
   * Returns a new object of class '<em>Aritmetico</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Aritmetico</em>'.
   * @generated
   */
  Aritmetico createAritmetico();

  /**
   * Returns a new object of class '<em>Expressao</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expressao</em>'.
   * @generated
   */
  Expressao createExpressao();

  /**
   * Returns a new object of class '<em>Desvio</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Desvio</em>'.
   * @generated
   */
  Desvio createDesvio();

  /**
   * Returns a new object of class '<em>Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Value</em>'.
   * @generated
   */
  Value createValue();

  /**
   * Returns a new object of class '<em>variavel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>variavel</em>'.
   * @generated
   */
  variavel createvariavel();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  P2Package getP2Package();

} //P2Factory
