/**
 * generated by Xtext 2.22.0
 */
package org.xtext.sisprog.p2;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.sisprog.p2.P2Package#getValue()
 * @model
 * @generated
 */
public interface Value extends Expressao
{
} // Value
