/*
 * generated by Xtext 2.22.0
 */
package org.xtext.sisprog.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.sisprog.p2.ui.internal.P2Activator;

public class P2UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return P2Activator.getInstance().getInjector("org.xtext.sisprog.P2");
	}

}
