/*
 * generated by Xtext 2.22.0
 */
package org.xtext.sisprog.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.sisprog.P2RuntimeModule;
import org.xtext.sisprog.P2StandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class P2IdeSetup extends P2StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new P2RuntimeModule(), new P2IdeModule()));
	}
	
}
