/**
 * generated by Xtext 2.22.0
 */
package org.xtext.sisprog.p2.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.sisprog.p2.Aritmetico;
import org.xtext.sisprog.p2.Atribuicao;
import org.xtext.sisprog.p2.P2Package;
import org.xtext.sisprog.p2.variavel;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Atribuicao</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sisprog.p2.impl.AtribuicaoImpl#getRes <em>Res</em>}</li>
 *   <li>{@link org.xtext.sisprog.p2.impl.AtribuicaoImpl#getAt <em>At</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AtribuicaoImpl extends ComandoImpl implements Atribuicao
{
  /**
   * The cached value of the '{@link #getRes() <em>Res</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRes()
   * @generated
   * @ordered
   */
  protected variavel res;

  /**
   * The cached value of the '{@link #getAt() <em>At</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAt()
   * @generated
   * @ordered
   */
  protected Aritmetico at;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AtribuicaoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return P2Package.Literals.ATRIBUICAO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public variavel getRes()
  {
    return res;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRes(variavel newRes, NotificationChain msgs)
  {
    variavel oldRes = res;
    res = newRes;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, P2Package.ATRIBUICAO__RES, oldRes, newRes);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRes(variavel newRes)
  {
    if (newRes != res)
    {
      NotificationChain msgs = null;
      if (res != null)
        msgs = ((InternalEObject)res).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - P2Package.ATRIBUICAO__RES, null, msgs);
      if (newRes != null)
        msgs = ((InternalEObject)newRes).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - P2Package.ATRIBUICAO__RES, null, msgs);
      msgs = basicSetRes(newRes, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, P2Package.ATRIBUICAO__RES, newRes, newRes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Aritmetico getAt()
  {
    return at;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAt(Aritmetico newAt, NotificationChain msgs)
  {
    Aritmetico oldAt = at;
    at = newAt;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, P2Package.ATRIBUICAO__AT, oldAt, newAt);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAt(Aritmetico newAt)
  {
    if (newAt != at)
    {
      NotificationChain msgs = null;
      if (at != null)
        msgs = ((InternalEObject)at).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - P2Package.ATRIBUICAO__AT, null, msgs);
      if (newAt != null)
        msgs = ((InternalEObject)newAt).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - P2Package.ATRIBUICAO__AT, null, msgs);
      msgs = basicSetAt(newAt, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, P2Package.ATRIBUICAO__AT, newAt, newAt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case P2Package.ATRIBUICAO__RES:
        return basicSetRes(null, msgs);
      case P2Package.ATRIBUICAO__AT:
        return basicSetAt(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case P2Package.ATRIBUICAO__RES:
        return getRes();
      case P2Package.ATRIBUICAO__AT:
        return getAt();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case P2Package.ATRIBUICAO__RES:
        setRes((variavel)newValue);
        return;
      case P2Package.ATRIBUICAO__AT:
        setAt((Aritmetico)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case P2Package.ATRIBUICAO__RES:
        setRes((variavel)null);
        return;
      case P2Package.ATRIBUICAO__AT:
        setAt((Aritmetico)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case P2Package.ATRIBUICAO__RES:
        return res != null;
      case P2Package.ATRIBUICAO__AT:
        return at != null;
    }
    return super.eIsSet(featureID);
  }

} //AtribuicaoImpl
