/**
 * generated by Xtext 2.22.0
 */
package org.xtext.sisprog.p2.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.sisprog.p2.Comando;
import org.xtext.sisprog.p2.P2Package;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Comando</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ComandoImpl extends MinimalEObjectImpl.Container implements Comando
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComandoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return P2Package.Literals.COMANDO;
  }

} //ComandoImpl
