/**
 * generated by Xtext 2.22.0
 */
package org.xtext.sisprog.p2.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.sisprog.p2.Comando;
import org.xtext.sisprog.p2.Comparacao;
import org.xtext.sisprog.p2.DesvioCondicional;
import org.xtext.sisprog.p2.P2Package;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Desvio Condicional</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sisprog.p2.impl.DesvioCondicionalImpl#getComparacao <em>Comparacao</em>}</li>
 *   <li>{@link org.xtext.sisprog.p2.impl.DesvioCondicionalImpl#getComandos <em>Comandos</em>}</li>
 *   <li>{@link org.xtext.sisprog.p2.impl.DesvioCondicionalImpl#getComando <em>Comando</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DesvioCondicionalImpl extends ComandoImpl implements DesvioCondicional
{
  /**
   * The cached value of the '{@link #getComparacao() <em>Comparacao</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComparacao()
   * @generated
   * @ordered
   */
  protected EList<Comparacao> comparacao;

  /**
   * The cached value of the '{@link #getComandos() <em>Comandos</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComandos()
   * @generated
   * @ordered
   */
  protected EList<Comando> comandos;

  /**
   * The cached value of the '{@link #getComando() <em>Comando</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComando()
   * @generated
   * @ordered
   */
  protected EList<Comando> comando;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DesvioCondicionalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return P2Package.Literals.DESVIO_CONDICIONAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Comparacao> getComparacao()
  {
    if (comparacao == null)
    {
      comparacao = new EObjectContainmentEList<Comparacao>(Comparacao.class, this, P2Package.DESVIO_CONDICIONAL__COMPARACAO);
    }
    return comparacao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Comando> getComandos()
  {
    if (comandos == null)
    {
      comandos = new EObjectContainmentEList<Comando>(Comando.class, this, P2Package.DESVIO_CONDICIONAL__COMANDOS);
    }
    return comandos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Comando> getComando()
  {
    if (comando == null)
    {
      comando = new EObjectContainmentEList<Comando>(Comando.class, this, P2Package.DESVIO_CONDICIONAL__COMANDO);
    }
    return comando;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case P2Package.DESVIO_CONDICIONAL__COMPARACAO:
        return ((InternalEList<?>)getComparacao()).basicRemove(otherEnd, msgs);
      case P2Package.DESVIO_CONDICIONAL__COMANDOS:
        return ((InternalEList<?>)getComandos()).basicRemove(otherEnd, msgs);
      case P2Package.DESVIO_CONDICIONAL__COMANDO:
        return ((InternalEList<?>)getComando()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case P2Package.DESVIO_CONDICIONAL__COMPARACAO:
        return getComparacao();
      case P2Package.DESVIO_CONDICIONAL__COMANDOS:
        return getComandos();
      case P2Package.DESVIO_CONDICIONAL__COMANDO:
        return getComando();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case P2Package.DESVIO_CONDICIONAL__COMPARACAO:
        getComparacao().clear();
        getComparacao().addAll((Collection<? extends Comparacao>)newValue);
        return;
      case P2Package.DESVIO_CONDICIONAL__COMANDOS:
        getComandos().clear();
        getComandos().addAll((Collection<? extends Comando>)newValue);
        return;
      case P2Package.DESVIO_CONDICIONAL__COMANDO:
        getComando().clear();
        getComando().addAll((Collection<? extends Comando>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case P2Package.DESVIO_CONDICIONAL__COMPARACAO:
        getComparacao().clear();
        return;
      case P2Package.DESVIO_CONDICIONAL__COMANDOS:
        getComandos().clear();
        return;
      case P2Package.DESVIO_CONDICIONAL__COMANDO:
        getComando().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case P2Package.DESVIO_CONDICIONAL__COMPARACAO:
        return comparacao != null && !comparacao.isEmpty();
      case P2Package.DESVIO_CONDICIONAL__COMANDOS:
        return comandos != null && !comandos.isEmpty();
      case P2Package.DESVIO_CONDICIONAL__COMANDO:
        return comando != null && !comando.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //DesvioCondicionalImpl
