/**
 * generated by Xtext 2.22.0
 */
package org.xtext.sisprog.p2.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.sisprog.p2.Desvio;
import org.xtext.sisprog.p2.Funcao;
import org.xtext.sisprog.p2.P2Package;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Desvio</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sisprog.p2.impl.DesvioImpl#getRotina <em>Rotina</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DesvioImpl extends ComandoImpl implements Desvio
{
  /**
   * The cached value of the '{@link #getRotina() <em>Rotina</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRotina()
   * @generated
   * @ordered
   */
  protected Funcao rotina;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DesvioImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return P2Package.Literals.DESVIO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Funcao getRotina()
  {
    if (rotina != null && rotina.eIsProxy())
    {
      InternalEObject oldRotina = (InternalEObject)rotina;
      rotina = (Funcao)eResolveProxy(oldRotina);
      if (rotina != oldRotina)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, P2Package.DESVIO__ROTINA, oldRotina, rotina));
      }
    }
    return rotina;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Funcao basicGetRotina()
  {
    return rotina;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRotina(Funcao newRotina)
  {
    Funcao oldRotina = rotina;
    rotina = newRotina;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, P2Package.DESVIO__ROTINA, oldRotina, rotina));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case P2Package.DESVIO__ROTINA:
        if (resolve) return getRotina();
        return basicGetRotina();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case P2Package.DESVIO__ROTINA:
        setRotina((Funcao)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case P2Package.DESVIO__ROTINA:
        setRotina((Funcao)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case P2Package.DESVIO__ROTINA:
        return rotina != null;
    }
    return super.eIsSet(featureID);
  }

} //DesvioImpl
