/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.sisprog.JJ.ui.internal.JJActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(JJActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		JJActivator activator = JJActivator.getInstance();
		return activator != null ? activator.getInjector(JJActivator.ORG_XTEXT_EXAMPLE_MYDSL_MYDSL) : null;
	}

}
