/*
 * generated by Xtext 2.22.0
 */
package org.xtext.sisprog.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.sisprog.p2.ui.internal.P2Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class P2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(P2Activator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		P2Activator activator = P2Activator.getInstance();
		return activator != null ? activator.getInjector(P2Activator.ORG_XTEXT_SISPROG_P2) : null;
	}

}
