/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.sisprog.JJ.ui.internal.JJActivator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return JJActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
