/*
 * generated by Xtext 2.22.0
 */
package org.xtext.sisprog.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractP2ScopeProvider extends DelegatingScopeProvider {
}
